# Generated by Django 5.2 on 2025-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_useractivity_user_id_alter_group_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='share_link',
            field=models.CharField(default='', max_length=256),
        ),
    ]
