# Generated by Django 5.2 on 2025-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_group_share_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='group',
            name='userprofiles',
            field=models.ManyToManyField(to='activity.userprofile'),
        ),
    ]
