# Generated by Django 5.2 on 2025-04-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_group_users_group_userprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
