# Generated by Django 5.2 on 2025-12-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='criteria_excel',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
